### ISSUE TITLE
customattrs: ['*'] doesn't work

### ISSUE THREAD

**Issue by weshardee** [ewu02/gulp-html-angular-validate#1]
Seems like the example options for custom attributes and custom tags does not work for a stream containing multiple files.

**Comment by ewu02** [comment]
can you provide an example? Options are passed directly to html-angular-validate. customattrs: ['*'] ignores all warnings about custom attrs for me, which is the expected result.

**Comment by weshardee** [comment]
The first file in a stream is handled correctly, but subsequent files are not. 

I did some more digging and it looks like the issue is actually in html-angular-validate rather than your gulp plugin, so I've submitted a pull request over there (https://github.com/nikestep/html-angular-validate/pull/4).
