### ISSUE TITLE
DeprecationWarning: Calling an asynchronous function without callback is deprecated.

### ISSUE THREAD

**Issue by ChrisMBarr** [ewu02/gulp-html-angular-validate#11]
When using Node 8.x and running my HTML linting steps I get **a ton** of deprecation warnings.  One per HTML file.  When there are errors, this makes it difficult to locate them.

![2017-08-28 08_24_51-](https://user-images.githubusercontent.com/463685/29773320-d4c3ab72-8bca-11e7-9ebb-7de30c6d7471.png)

I do realize that this might be an issue with `html-angular-validate` itself and not this gulp plugin. I will happily open an issue with that project if it's determined that these warnings are not due to this project.

**Comment by ChrisMBarr** [comment]
@ewu02 any word on this?  Is it possible to tell if this comes from this project or from `html-angular-validate` itself?

**Comment by ewu02** [comment]
@chrismbarr Apologize for the late response. I don't believe it came from this project as all async functions have callbacks. I could be mistaken though as this project is no longer maintained. In any case, feel free to open a PR or take over this project if you like.
